version: '3'

services:
  nextjs:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    # Add environment variables if needed
    # environment:
    #   - DATABASE_URL=postgres://user:password@postgres:5432/dbname
    #   - NEXT_PUBLIC_API_URL=https://api.example.com