version: '3'

services:
  nextjs-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # Mount the source code into the container for hot reloading
      - ./:/app
      # Don't mount node_modules - use container's version
      - /app/node_modules
      # Don't mount .next folder - let it be built inside the container
      - /app/.next
      # Persist sqlite db and image uploads
      - sqlite-data:/app/prisma
      - image-uploads:/app/public/uploads
    env_file:
      - .env
    # command: npm run dev

volumes:
  sqlite-data:
    driver: local
  image-uploads:
    driver: local