version: '3'

services:
  nextjs-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # Mount the source code into the container for hot reloading
      - ./:/app
      # Don't mount node_modules - use container's version
      - /app/node_modules
      # Don't mount .next and prisma folder - let it be built inside the container
      - /app/.next
      - /app/prisma
    env_file:
      - .env
